#apiVersion: v1
#kind: Service
#metadata:
#  name: demo-external-svc
#spec:
#  selector:
#    app.kubernetes.io/name: demo
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 7080
#  type: LoadBalancer

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: demo
  name: demo
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - demo
        - --id=0
        - --kvhost=http://diskv-loadbalancing-svc
        - --int=http://diskv-svc-%s:9080
        - --incp
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: pod-admin
status: {}