apiVersion: v1
kind: Service
metadata:
  name: diskv-loadbalancing-svc
spec:
  selector:
    app: diskv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
---

apiVersion: v1
kind: Service
metadata:
  name: diskv-svc-0
spec:
  selector:
    app.kubernetes.io/name: diskv-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7340
      name: rpc
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: diskv
    app.kubernetes.io/name: diskv-0
  name: diskv-0
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - start
        - --id=0
        - --peers=diskv-svc-1,diskv-svc-2,diskv-svc-3,diskv-svc-4
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: diskv-svc-1
spec:
  selector:
    app.kubernetes.io/name: diskv-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7340
      name: rpc
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: diskv
    app.kubernetes.io/name: diskv-1
  name: diskv-1
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - start
        - --id=1
        - --peers=diskv-svc-0,diskv-svc-2,diskv-svc-3,diskv-svc-4
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: diskv-svc-2
spec:
  selector:
    app.kubernetes.io/name: diskv-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7340
      name: rpc
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: diskv
    app.kubernetes.io/name: diskv-2
  name: diskv-2
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - start
        - --id=2
        - --peers=diskv-svc-0,diskv-svc-1,diskv-svc-3,diskv-svc-4
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: diskv-svc-3
spec:
  selector:
    app.kubernetes.io/name: diskv-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7340
      name: rpc
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: diskv
    app.kubernetes.io/name: diskv-3
    network: partition
  name: diskv-3
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - start
        - --id=3
        - --peers=diskv-svc-0,diskv-svc-1,diskv-svc-2,diskv-svc-4
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: diskv-svc-4
spec:
  selector:
    app.kubernetes.io/name: diskv-4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7340
      name: rpc
    - protocol: TCP
      port: 9080
      targetPort: 9080
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: diskv
    app.kubernetes.io/name: diskv-4
    network: partition
  name: diskv-4
spec:
  containers:
    - command:
        - /app/dizkv
      args:
        - start
        - --id=4
        - --peers=diskv-svc-0,diskv-svc-1,diskv-svc-2,diskv-svc-3
      image: aravindarc/dizkv:1.22
      name: default
      resources: {}
      imagePullPolicy: Always
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
